In [2]:
!pip install jedi

  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)


In [4]:
import matplotlib
import numpy as np
import seaborn as sns
import pandas as pd
import sklearn as sk
import sys
import matplotlib.pyplot as plt

from jedi.api.refactoring import inline

#from sklearn.datasets import load_boston
from sklearn.datasets import fetch_openml

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RANSACRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor

from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
sns.set_style("whitegrid")
#%matplotlib inline()
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import validation_curve
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression




In [12]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

raw_df.head()





0      1      2    3      4      5     6       7    8      9     10
0    0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
1  396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
2    0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
3  396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
4    0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8

In [13]:
#boston = load_boston()

boston.data.shape, boston.target.shape

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.4, random_state=0)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

regression = svm.SVR(kernel='linear', C=1).fit(X_train, y_train)        # SUPPORT VECTOR REGRESSION
reg_score = regression.score(X_test, y_test)
print(reg_score)


(303, 13)
(203, 13)
(303,)
(203,)
0.667431382173115


In [18]:

# 2. Computing cross-validated metrics
regresssion = svm.SVR(kernel='linear', C=1)
scores = cross_val_score(regression, data, target, cv=5)
print(scores)

print("Accuracy: %0.2f (+- %0.2f)" % (scores.mean(), scores.std() ** 2))

scores = cross_val_score(regression, data, target, cv=5, scoring='neg_mean_squared_error')
print(scores)



#3. Kfold
X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)

for train, test in kf.split(X):
    print("%s %s" % (train, test))



[0.77285459 0.72771739 0.56131914 0.15056451 0.08212844]
[ -7.84451123 -24.78772444 -35.13272326 -74.50555945 -24.40465975]
[2 3] [0 1]
[0 1] [2 3]


In [19]:


# 4. Stratified Kfold Se utiliza para datos no balanceados
X = np.ones(10)
y = [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
skf = StratifiedKFold(n_splits=3)

for train, test in skf.split(X, y):
    print("%s %s" % (train, test))


# 5 Pipeline

pipe_svm = make_pipeline(StandardScaler(), PCA(n_components=2), svm.SVR(kernel='linear', C=1))  # PCA resume los datos
pipe_svm.fit(X_train, y_train)
y_pred = pipe_svm.predict(X_test)
print('Test Accuracy: %0.3f' % pipe_svm.score(X_test, y_test))


scores= cross_val_score(estimator=pipe_svm, X=X_train, y = y_train, cv=10, n_jobs=1)
print('CV accuracy scores: %s' % scores)

[2 3 6 7 8 9] [0 1 4 5]
[0 1 3 4 5 8 9] [2 6 7]
[0 1 2 4 5 6 7] [3 8 9]
Test Accuracy: 0.391
CV accuracy scores: [0.63971176 0.43579197 0.46977821 0.25027246 0.5124364  0.26221374
 0.30877195 0.54528563 0.37810066 0.47313549]
